### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by XVicarious** [XVicarious/file_hash#1]
Need to split files into digestible chunks. 100MB maybe? Configurable, that's it.

```
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing /media/downloads/seeding/[HorribleSubs] Akkun to Kanojo - 20 [720p].mkv
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing with algorithm: blake2b
2018-10-27 03:59 DEBUG    file_hash     collect_complete_files [HorribleSubs] Akkun to Kanojo - 20 [720p]:\nhash: f6cd5737dae643cdbded8cec55c79c632019b2d75f164b2fae5fe33f9814ccd07f31e84c7adf7f96debe356b4ce6c048d9439749032ba996ce990a493f8d4ba9\nmtime: 1534519974.389479\nbyes: 48651507
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing /media/downloads/seeding/[Erai-raws] Shoujo Kageki Revue Starlight - 11 [720p][Multiple Subtitle].mkv
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing with algorithm: blake2b
2018-10-27 03:59 DEBUG    file_hash     collect_complete_files [Erai-raws] Shoujo Kageki Revue Starlight - 11 [720p][Multiple Subtitle]:\nhash: 5c383ed70ebb98894b831008ece74703c6d42ac0e206258af20b76387c9d7e8db1535d5146c61cfd132f092a9ab07899e043e460ab3ac92a3e445340e12665b8\nmtime: 1538625677.7178843\nbyes: 147434571
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing /media/downloads/seeding/[HA／ss／] Sunohara-sou no Kanrinin-san - 10 [C0BBA196].mkv
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing with algorithm: blake2b
2018-10-27 03:59 DEBUG    file_hash     collect_complete_files [HA／ss／] Sunohara-sou no Kanrinin-san - 10 [C0BBA196]:\nhash: 2b411e4737da6438d384e3316b9bfb2bf9427b73c39f9046d85447ada3455724714d16d89721fd75e7b1978f4cbd163f34976e842fbea6a4b8ff93fbc901af73\nmtime: 1536455754.0\nbyes: 222315361
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing /media/downloads/seeding/Its.Always.Sunny.in.Philadelphia.S13E05.The.Gang.Gets.New.Wheels.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]/RARBG.txt
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing with algorithm: blake2b
2018-10-27 03:59 DEBUG    file_hash     collect_complete_files RARBG:\nhash: c3103d005bf5ebe9222e9a7ac9136cb97e2075f373d56ddaee7f29137b6e843afe1dc883888fd7485a89116928e156f36f4256633f94559e1b28b9d2581b6c96\nmtime: 1534391981.3110278\nbyes: 30
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing /media/downloads/seeding/Its.Always.Sunny.in.Philadelphia.S13E05.The.Gang.Gets.New.Wheels.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]/Its.Always.Sunny.in.Philadelphia.S13E05.The.Gang.Gets.New.Wheels.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing with algorithm: blake2b
2018-10-27 03:59 WARNING  apscheduler.scheduler                 Execution of job "download_anime (trigger: interval[0:20:00], next run at: 2018-10-27 03:59:28 EDT)" skipped: maximum number of running instances reached (1)
2018-10-27 03:59 DEBUG    file_hash     collect_complete_files Its.Always.Sunny.in.Philadelphia.S13E05.The.Gang.Gets.New.Wheels.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb:\nhash: 98729201d036c64b9b1ab8b7bfee6209be357c4c2612a52214bef50719e67f800482243d49cce01012e6a5ecc4eae9443b8ca66c3e8694f2257233e3b4128c22\nmtime: 1538643698.1400626\nbyes: 1895645086
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing /media/downloads/seeding/The.Hateful.Eight.2015.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-RARBG/The.Hateful.Eight.2015.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-RARBG.nfo
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing with algorithm: blake2b
2018-10-27 03:59 DEBUG    file_hash     collect_complete_files The.Hateful.Eight.2015.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-RARBG:\nhash: 95b6090cde79ffccefa60f39a268d2342230c761cc0aa35c6a8926480344b509caf48830e8cd164470a56f9a3799b2eaaca5dda967c3ec87e9ea0399e0843263\nmtime: 1536632804.9134138\nbyes: 7942
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing /media/downloads/seeding/The.Hateful.Eight.2015.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-RARBG/RARBG.com.txt
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing with algorithm: blake2b
2018-10-27 03:59 DEBUG    file_hash     collect_complete_files RARBG.com:\nhash: af3e6852dc29c6326f5e6b44b1ae39707c426f586f74d4bfc4f4567ca2cb758dc3f7427a74f18866572d9f18f364193dd8c88d8715d6de248a08daace2ba1dea\nmtime: 1538431057.9458773\nbyes: 34
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing /media/downloads/seeding/The.Hateful.Eight.2015.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-RARBG/The.Hateful.Eight.2015.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-RARBG.mkv
2018-10-27 03:59 VERBOSE  file_hash     collect_complete_files Hasing with algorithm: blake2b
2018-10-27 03:59 CRITICAL task          collect_complete_files BUG: Unhandled error in plugin file_hash: 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/config/plugins/file_hash/file_hash.py", line 56, in on_task_metainfo
    current_hasher.update(to_hash.read())
MemoryError
```

**Comment by XVicarious** [comment]
Fixed in 9a6f...
